modLoader = "javafml"
loaderVersion = "[47,)"
license = "Custom"

[[mods]]
modId = "farm_and_charm"
version = "${version}"
displayName = "[Let's Do] Farm & Charm"
authors = "satisfy, cristelknight123"
description = '''
The farm calls: Experience the art of advanced agriculture and farmhouse cuisine! Use mincers, cooking pots, as well as new grains and fruit varieties to enhance your culinary and agricultural skills.
'''
logoFile = "pack.png"

[[dependencies.farm_and_charm]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.farm_and_charm]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.farm_and_charm]]
modId = "doapi"
mandatory = true
versionRange = "[1.2.11,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.farm_and_charm]]
modId = "architectury"
mandatory = true
versionRange = "[9.0.8,)"
ordering = "AFTER"
side = "BOTH"